### ISSUE TITLE
JobJobExtended fails spec file validation

### ISSUE THREAD

**Issue by cbrainerd** [Isilon/isilon_sdk#10]
>   "name": "SyntaxError",
>   "message": "Swagger schema validation failed.
>   Data does not match any schemas from 'oneOf' at #/paths//platform/1/job/jobs/{JobJobId}/get/responses/200
>     Data does not match any schemas from 'oneOf' at #/paths//platform/1/job/jobs/{JobJobId}/get/responses/200/schema
>       Data does not match any schemas from 'anyOf' at #/schema/properties/jobs/items
>         Data does not match any schemas from 'anyOf' at #/properties/jobs/items/properties/paths/items
>           **Expected type array but found type boolean at #/properties/paths/items/required**
>           Expected type array but found type object at #/properties/paths/items
>         Expected type array but found type object at #/properties/jobs/items
>       Additional properties not allowed: properties at #/schema
>     Missing required property: $ref at #/paths//platform/1/job/jobs/{JobJobId}/get/responses/200

Draft 3 style `required` attributes appear in spec file. Swagger spec requires draft 4 style `required` attributes. 

```
                "participants": {
                    "description": "The set of devids working on the job.",
                    "items": {
                        "required": true,
                        "type": "integer"
                    },
                    "type": "array"
                },
                "paths": {
                    "description": "Paths for which the job was queued.",
                    "items": {
                        "required": true,
                        "type": "string"
                    },
                    "type": "array"
                },
```

create_swagger_config.py seems to correctly convert a number of these required attributes for this definition, just not the above 2. 

Attrs converted to v4 style:

```
            "required": [
                "impact",
                "type",
                "state",
                "priority",
                "create_time",
                "policy",
                "retries_remaining",
                "total_phases",
                "id"
            ],
```

**Comment by Atomicology** [comment]
This issue is affecting the following Python packages: `isi_sdk_7_2`, `isi_sdk_8_0`, and `isi_sdk_8_0_1`.
