### ISSUE TITLE
api_instance.list_providers_ads() parameter validation for home_directory_template is incorrect

### ISSUE THREAD

**Issue by VortexUK** [Isilon/isilon_sdk#102]
We got this error from the latest version of the SDK:

Invalid value for `home_directory_template`, must be a follow pattern or equal to `/^((\/[^\/[:cntrl:]]+)(\/?))*$/`

When  checking using the CLI what the value was set to, it was this:
```
isi auth ads view CONTOSO.COM --verbose
...
Home Directory Template: /ifs/home/%D/%U
```

Which is valid (it sets it to the ADS Zone/Username)

Code used:
```
import isilon_sdk.v9_5_0 as isi_sdk
configuration = isi_sdk.Configuration()
configuration.host = "https://admin.isilon.contoso.com:8080"
configuration.username = "user"
configuration.password = "pass"
api_instance = isi_sdk.AuthApi(isi_sdk.ApiClient(configuration))
api_response: Any = api_instance.list_providers_ads() <--- Errors
```
Version of the SDK:
`isilon-sdk==0.3.0.1`
Version of OneFS on the cluster:
```
isi version
Isilon OneFS 9.8.0.1 (Release, Build B_MR_9_8_0_1_018(RELEASE), 2024-06-05 17:12:58, 0x908005000100012)
```

**Comment by mmanwani07** [comment]
How 9.8 version schema support 9.5 ?? The new release will be available by today, kindly target to use the same.

**Comment by mmanwani07** [comment]
Based on my above comment you wiil be able to access the details because you are using 9.8 version which were earlier not supported
