### ISSUE TITLE
api_instance.get_http_settings() validation is incorrect

### ISSUE THREAD

**Issue by VortexUK** [Isilon/isilon_sdk#103]
When attempting to run this against a cluster, I get:

ValueError: Invalid value for `inactive_timeout`, must be a value greater than or equal to `60`

However when I look at the value on the cluster:
```
isi http settings view
            Access Control: No
      Basic Authentication: No
    WebHDFS Ran HTTPS Port: 8443
                       Dav: No
         Enable Access Log: Yes
                     HTTPS: No
 Integrated Authentication: No
               Server Root: /ifs
                   Service: disabled
           Service Timeout: 8m20s
          Inactive Timeout: Now       <----------
           Session Max Age: 4H
Httpd Controlpath Redirect: No
```
It doesn't even specify an integer. Running:
```
 isi http settings modify --revert-inactive-timeout
 ```
 Which suggests in the help that it will `-- Set value to system default for --inactive-timeout.`

Does not change this. Can the validation be corrected please

Version of the SDK:
`isilon-sdk==0.3.0.1`
Version of OneFS on the cluster:
```
isi version
Isilon OneFS 9.8.0.1 (Release, Build B_MR_9_8_0_1_018(RELEASE), 2024-06-05 17:12:58, 0x908005000100012)
```

**Comment by mmanwani07** [comment]
How 9.8 version schema support 9.5 ?? The new release will be available by today, kindly target to use the same.
