### ISSUE TITLE
api_instance.get_performance_settings() property validation is also incorrect

### ISSUE THREAD

**Issue by VortexUK** [Isilon/isilon_sdk#104]
Getting real tired of this:

api_response: Any = api_instance.get_performance_settings()
ValueError: Invalid value for `max_health_multiplier_unhealthy`, must be a value less than or equal to `10.0`

Same as the other issues, to be honest I don't know why you have put such strict validation on a GET request in the first place - the data is what the cluster says it is, not what your SDK thinks it is. See the other 2 issues for more detail on the setup.

**Comment by mmanwani07** [comment]
How 9.8 version schema support 9.5 ?? The new release will be available by today, kindly target to use the same.
