### ISSUE TITLE
Spec file validation: /paths/platform/1/auth/mapping/identities/{MappingIdentityId}/post is missing path parameter(s) for {MappingIdentityId}"

### ISSUE THREAD

**Issue by cbrainerd** [Isilon/isilon_sdk#11]
> {
>   "name": "SyntaxError",
>   **"message": "Validation failed. /paths/platform/1/auth/mapping/identities/{MappingIdentityId}/post is missing path parameter(s) for {MappingIdentityId}",**
>   "stack": "SyntaxError: Validation failed. /paths/platform/1/auth/mapping/identities/{MappingIdentityId}/post is missing path parameter(s) for {MappingIdentityId}
>     at Function.ono [as syntax](/Volumes/Git/sdk-test/node_modules/ono/lib/index.js:67:20)
>     at validatePathParameters (/Volumes/Git/sdk-test/node_modules/swagger-parser/lib/validate-spec.js:174:15)
>     at validateParameters (/Volumes/Git/sdk-test/node_modules/swagger-parser/lib/validate-spec.js:99:3)
>     at /Volumes/Git/sdk-test/node_modules/swagger-parser/lib/validate-spec.js:45:7
>     at Array.forEach (native)
>     at validatePath (/Volumes/Git/sdk-test/node_modules/swagger-parser/lib/validate-spec.js:40:18)
>     at /Volumes/Git/sdk-test/node_modules/swagger-parser/lib/validate-spec.js:25:7
>     at Array.forEach (native)
>     at validateSpec (/Volumes/Git/sdk-test/node_modules/swagger-parser/lib/validate-spec.js:20:9)
>     at /Volumes/Git/sdk-test/node_modules/swagger-parser/lib/index.js:161:9"
> }

In the paths section, for "/platform/1/auth/mapping/identities/{MappingIdentityId}" the post operation does not map {MappingIdentityId} from the path. 

``` json
            "post": {
                "description": "Manually set or modify a mapping between two personae.",
                "operationId": "createMappingIdentity",
                "parameters": [
                    {
                        "description": "Desired mapping target to fetch/generate.",
                        "enum": [
                            "uid",
                            "gid",
                            "sid"
                        ],
                        "in": "query",
                        "name": "type",
                        "type": "string"
                    },
                    {
                        "description": "Optional zone.",
                        "in": "query",
                        "name": "zone",
                        "type": "string"
                    },
                    {
                        "in": "body",
                        "name": "MappingIdentity",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Empty"
                        }
                    }
                ],
```

To resolve this validation failure, there should be an additional parameter:

``` json
                    {
                       "in": "path",
                       "name": "MappingIdentityId",
                       "required": true,
                       "type": "string"
                    },
```

Found in v0.1.2 isi_sdk_7_2/output.json.

**Comment by Atomicology** [comment]
This issue is affecting the following Python packages: `isi_sdk_7_2`, `isi_sdk_8_0`, `isi_sdk_8_0_1`, and `isi_sdk_8_1_0`.
