### ISSUE TITLE
Spec file validation: Failures due to misspellings in PAPI schemas

### ISSUE THREAD

**Issue by cbrainerd** [Isilon/isilon_sdk#12]
>   "name": "SyntaxError",
>   "message": "Swagger schema validation failed.
>   Data does not match any schemas from 'oneOf' at #/paths//platform/1/debug/stats/get/responses/200
>     Data does not match any schemas from 'oneOf' at #/paths//platform/1/debug/stats/get/responses/200/schema
>       Data does not match any schemas from 'anyOf' at #/schema/properties/handlers/items
>         **Additional properties not allowed: descriprion at #/properties/handlers/items/properties/name**
>         Expected type array but found type object at #/properties/handlers/items
>       Additional properties not allowed: properties at #/schema
>     Missing required property: $ref at #/paths//platform/1/debug/stats/get/responses/200
> 
>   "name": "SyntaxError",
>   "message": "Swagger schema validation failed.
>   Data does not match any schemas from 'oneOf' at #/paths//platform/1/auth/access/{AuthAccessUser}/get/responses/200
>     Data does not match any schemas from 'oneOf' at #/paths//platform/1/auth/access/{AuthAccessUser}/get/responses/200/schema
>       Data does not match any schemas from 'anyOf' at #/schema/properties/access/items
>         **Additional properties not allowed: descriptoin at #/properties/access/items/properties/id**
>         Expected type array but found type object at #/properties/access/items
>       Additional properties not allowed: properties at #/schema
>     Missing required property: $ref at #/paths//platform/1/auth/access/{AuthAccessUser}/get/responses/200

2 spec file validation failures occur due to misspelled attribute names that are passed through to the spec file. There are 2 variations on the spelling of "description" that cause these failures:
- `descriprion` at /platform/1/debug/stats/get/responses/200/schema
- `descriptoin` at /platform/1/auth/access/{AuthAccessUser}/get/responses/200

These misspellings are fixed in OneFS in later releases, but to generate a compliant spec file for existing OneFS versions create_swagger_config.py would need to correct these when generating the spec file.

**Comment by Atomicology** [comment]
This issue is only affecting the isi_sdk_7_2 Python package.
