### ISSUE TITLE
Spec file validation fail: Expected type object but found type array at #/properties/operations/items/properties/operations

### ISSUE THREAD

**Issue by cbrainerd** [Isilon/isilon_sdk#13]
>   "name": "SyntaxError",
>   "message": "Swagger schema validation failed.
>   Data does not match any schemas from 'oneOf' at #/paths//platform/3/statistics/operations/get/responses/200
>     Data does not match any schemas from 'oneOf' at #/paths//platform/3/statistics/operations/get/responses/200/schema
>       Data does not match any schemas from 'anyOf' at #/schema/properties/operations/items
>         Expected type object but found type array at #/properties/operations/items/properties/operations
>         Expected type array but found type object at #/properties/operations/items
>       Additional properties not allowed: properties at #/schema
>     Missing required property: $ref at #/paths//platform/3/statistics/operations/get/responses/200

The root of this problem is an invalid PAPI GET_output_schema for /platform/3/statistics/operations. This should be fixed in a future OneFS release (bug 176250), but for existing releases create_swagger_config.py would need to handle this to generate a compliant spec file. 

Here's the offending bit in the spec file. The "operations" array is where the trouble starts:

``` json
        "StatisticsOperation": {
            "properties": {
                "operations": [ 
                    {
                        "operation": {
                            "description": "The name of the operation.",
                            "required": true,
                            "type": "string"
                        }
                    }
                ]
            },
            "type": "object"
        },
```

Found in v0.1.2 isi_sdk_8_0/output.json

**Comment by Atomicology** [comment]
This issue is affecting the following Python packages: `isi_sdk_8_0` and `isi_sdk_8_0_1`.
