### ISSUE TITLE
Spec file validation fail: EventEventgroupOccurrencesEventgroup-Occurrence

### ISSUE THREAD

**Issue by cbrainerd** [Isilon/isilon_sdk#15]
>  "name": "SyntaxError",
>   "message": "Swagger schema validation failed.
>   Data does not match any schemas from 'oneOf' at #/paths//platform/3/event/eventgroup-occurrences/{EventEventgroupOccurrenceId}/get/responses/200
>     Data does not match any schemas from 'oneOf' at #/paths//platform/3/event/eventgroup-occurrences/{EventEventgroupOccurrenceId}/get/responses/200/schema
>       Data does not match any schemas from 'anyOf' at #/schema/properties/eventgroup-occurrences/items
>         Data does not match any schemas from 'anyOf' at #/properties/eventgroup-occurrences/items/properties/causes/items
>           **Data does not match any schemas from 'anyOf' at #/properties/causes/items/type**
>             No enum match for: {\"description\":\"Event Group cause as name and description\",\"items\":{\"type\":\"string\"},\"type\":\"array\"} at #/type
>             Expected type array but found type object at #/type
>           Expected type array but found type object at #/properties/causes/items
>         Expected type array but found type object at #/properties/eventgroup-occurrences/items
>       Additional properties not allowed: properties at #/schema
>     Missing required property: $ref at #/paths//platform/3/event/eventgroup-occurrences/{EventEventgroupOccurrenceId}/get/responses/200

create_swagger_config.py is passing a bad PAPI schema through to the spec file. The bad schema originates as the GET_output_schema for /platform/3/event/eventgroup-occurrences. 

This should be fixed in a future release of OneFS (bug 176274), however to generate a compliant spec file for existing releases create_swagger_config.py will need to correct the schema for the spec file. 

Found in v0.1.2 isi_sdk_8_0/output.json

**Comment by Atomicology** [comment]
This issue is only affecting the `isi_sdk_8_0` Python package.
