### ISSUE TITLE
isi_sdk.NetworkApi get_network_interfaces incorrect output

### ISSUE THREAD

**Issue by folijosvanagas** [Isilon/isilon_sdk#22]
Hello,
When I run isi_sdk.NetworkApi function get_network_interfaces() I receive this output. There is no information for interfaces. Variable type is none, although total interface count is valid.
{'interface': None, 'resume': None, 'total': 6}

I am able to retrieve correct output when I query /platform/3/network/interfaces link directly

**Comment by Atomicology** [comment]
This issue has been resolved in the [isi-sdk-8-1-0](https://pypi.org/project/isi-sdk-8-1-0/) package, but has not yet been back ported to isi-sdk-8-0 and isi-sdk-8-0-1.

**Comment by Atomicology** [comment]
The fix for this issue has been back ported to all package versions as of the [v0.2.0](https://github.com/Isilon/isilon_sdk/releases/tag/0.2.0) release.
