### ISSUE TITLE
HDFS, Swift, and other settings cannot be changed per-zone on 8.0+

### ISSUE THREAD

**Issue by ro-ket** [Isilon/isilon_sdk#23]
The HDFS protocol settings and Swift protocol settings and some other settings do not accept a zone argument through the SDK. Also some other protocols or auth settings are missing arguments.

**Comment by cbrainerd** [comment]
Release [0.1.7](https://github.com/Isilon/isilon_sdk/releases/tag/0.1.7) was built against OneFS 8.0.0.5 and should pick up the schemas fixes in that MR.

**Comment by cbrainerd** [comment]
This should be resolved in [0.1.9](https://github.com/Isilon/isilon_sdk/releases/tag/0.1.9) for `isi_sdk_8_0` and `isi_sdk_8_1_0`
