### ISSUE TITLE
Issue with Limit and Resume with get_smb_openfiles

### ISSUE THREAD

**Issue by adamrfox** [Isilon/isilon_sdk#24]
So, I have some code which I will include below which uses a limit to restrict the number SMB openfiles the call does at a time.  The first time I run it, I get the proper number along with a resume key.  However, when I try to run the call again with the resume key, I get a empty data set.  This does not seem to be the issue with other calls such as listing snapshots. 
[openfiles.txt](https://github.com/Isilon/isilon_sdk/files/920975/openfiles.txt)

Here is the output:

Not a resume call
{'openfiles': [{'file': 'C:\\ifs\\data\\PDF\\007.pdf',
                'id': 7247,
                'locks': 0,
                'permissions': ['read'],
                'user': 'Administrator'},
               {'file': 'C:\\ifs\\data\\PDF\\Aesops_Fables_T.pdf',
                'id': 7373,
                'locks': 0,
                'permissions': ['read'],
                'user': 'Administrator'},
               {'file': 'C:\\ifs\\data\\PDF\\catalog_aso.pdf',
                'id': 7539,
                'locks': 0,
                'permissions': ['read'],
                'user': 'Administrator'},
               {'file': 'C:\\ifs\\data\\PDF\\Around_the_World_in_80_Days_T.pdf',
                'id': 7485,
                'locks': 0,
                'permissions': ['read'],
                'user': 'Administrator'},
               {'file': 'C:\\ifs\\data\\PDF\\4233.pdf',
                'id': 7287,
                'locks': 0,
                'permissions': ['read'],
                'user': 'Administrator'},
               {'file': 'C:\\ifs\\data\\PDF\\Alices_Adventures_in_Wonderland_T.pdf',
                'id': 7411,
                'locks': 0,
                'permissions': ['read'],
                'user': 'Administrator'},
               {'file': 'C:\\ifs\\data\\PDF\\aoa.pdf',
                'id': 7449,
                'locks': 0,
                'permissions': ['read'],
                'user': 'Administrator'},
               {'file': 'C:\\ifs\\data\\PDF\\boxman.pdf',
                'id': 7503,
                'locks': 0,
                'permissions': ['read'],
                'user': 'Administrator'},
               {'file': 'C:\\ifs\\data\\PDF',
                'id': 6749,
                'locks': 0,
                'permissions': ['read'],
                'user': 'Administrator'},
               {'file': 'C:\\ifs\\data\\PDF\\Globes.pdf',
                'id': 7577,
                'locks': 0,
                'permissions': ['read'],
                'user': 'Administrator'}],
 'resume': '2-2-MTAA10-NDI5NDk2NzI4MwAA',
 'total': 24}
DEB: RESUME CALL
{'openfiles': [], 'resume': None, 'total': 24}

**Comment by Atomicology** [comment]
I am not able to consistently reproduce this issue. When running this same script against the latest Python language bindings, I sometimes receive back consecutive responses with the resume token, but sometimes not. This same issue appears to be present when issuing the queries against PAPI directly. Thus, this does not appear to be an SDK issue.
