### ISSUE TITLE
PEP 8: use of underscores is discouraged on package name

### ISSUE THREAD

**Issue by trunet** [Isilon/isilon_sdk#25]
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

"Python packages should also have short, all-lowercase names, although the use of underscores is discouraged."

This is causing problems when you add isi_sdk_7_2 to setup.py install_requires, as it converts the underscore to dashes making the package not being found.

**Comment by dmtucker** [comment]
@trunet I don't disagree; however, I am not able to reproduce this. How are you installing?

I used this `install_requires` in `setup.py`:
``` python
    install_requires=[
        'isi_sdk_8_0 ~= 0.1.4',
        ...
    ],
```
This is how I installed:
``` sh
pip install .  # pip 9.0.1 in a Python 3.4.2 virtualenv
```
Everything seemed to work fine during installation:
```
Processing /media/dtucker/SSD/projects/conductor
Collecting isi_sdk_8_0~=0.1.4 (from conductor==0.4.0)
  Downloading isi_sdk_8_0-0.1.5-py2.py3-none-any.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 446kB/s
...
```

**Comment by pmoranga** [comment]
@dmtucker Looks like the issue was due to old virtualenv package, it was installing an older pip package.

After updating virtualenv to latest, the installation using underscore works, pip is handling the non conformity issue.

```
$ pip install isi_sdk_7_2 
Collecting isi_sdk_7_2
Collecting python-dateutil (from isi_sdk_7_2)
Requirement already satisfied: six>=1.10 in ./.pyenv/lib/python2.7/site-packages (from isi_sdk_7_2)
Requirement already satisfied: urllib3>=1.15 in ./.pyenv/lib/python2.7/site-packages (from isi_sdk_7_2)
Collecting certifi (from isi_sdk_7_2)
Installing collected packages: python-dateutil, certifi, isi-sdk-7-2
Successfully installed certifi-2017.4.17 **isi-sdk-7-2-0.1.5** python-dateutil-2.6.0
```

Notice that on the final line it shows the package name with the substitutions.
You can close this Issue.

**Comment by trunet** [comment]
Due to the huge amount of work that is needed to rename the package, I think it's ok to close this issue as using latest virtualenv is working. If you want to rename, just reopen it.

Thanks...

**Comment by dmtucker** [comment]
FWIW, I have the latest virtualenv on my Debian workstation, but I still get pip 1.5.6 in new virtualenvs. So I try to make it a habit to upgrade `pip` and `setuptools` every time I make a new one... Anyways, glad we got this resolved :+1:

**Comment by pmoranga** [comment]
@dmtucker yeah, the same issue we had, the OS provided virtualenv was not new enough. just the latest virtualenv (15.1.0 (2016-11-15)) deliver the pip > 9.
CentOS and Debian latest packages still are quite old.
