### ISSUE TITLE
No SDK for /namespace

### ISSUE THREAD

**Issue by brettdbrown** [Isilon/isilon_sdk#39]
Customers need a way through the SDK to access the filesytem.  The customer I spoke to is
looking to automate SyncIQ policy creation and needs to be able to view the directory on OneFS.  Right now you can only do it outside of the sdk using curl.

**Comment by Atomicology** [comment]
Resolved in the [v0.2.3](https://github.com/Isilon/isilon_sdk/releases/tag/0.2.3) release.
