### ISSUE TITLE
Papi Schema Definitions - Missing Attributes within NameSpaceObject

### ISSUE THREAD

**Issue by peetie2k** [Isilon/isilon_sdk#68]
Hi,
The NamesSpaceObject definitions in the papi_schema (https://github.com/Isilon/isilon_sdk/blob/master/papi_schemas/definitions.json) misses the container/container_path attributes. When searching recursively this is really required and currently this gets omitted by conversion into the swagger model class.
Please fix that :)

Cheers,
Peter

**Comment by Atomicology** [comment]
@peetie2k: Thank you for identifying these missing attributes. They were not documented in the [File system access API](http://doc.isilon.com/onefs/8.1.0/api/04-ifs-br-file-system-access-apis.htm) under the "Common namespace attributes" so I missed them in the first pass. I will post a PR to add these.

**Comment by Atomicology** [comment]
This issue is resolved in the v0.2.4 release of the SDK.
