### ISSUE TITLE
There is no SDK release for OneFS 8.2.0

### ISSUE THREAD

**Issue by sjorge** [Isilon/isilon_sdk#77]
There is currently no SDK release for OneFS 8.2.0, the most recent one for 8.1.1 has some issues.

For example when calling create_smb_share it complains about unable to set the id field.

**Comment by nalinkanwar** [comment]
We're already working on this; We will release SDK for 8.2.0 somewhere in the upcoming week.

**Comment by nalinkanwar** [comment]
Released a new version for 8_2_0; Please file a new issue if the problem persists.
