### ISSUE TITLE
SDK 8.1.0 has issues setting duration for snapshot schedule

### ISSUE THREAD

**Issue by sjorge** [Isilon/isilon_sdk#78]
When using the API to create or update the duration field of a snapshot schedule the store value is not the as the supplied value.

Setting `608400` will actually result in `694800` being returned when querying the schedule at a later time.

The actually value is always bigger than the set value. When using the WebUI it is possible to set `608400`, when querying the value with the API I do get the correct result.

As far as I can tell the duration that is send via the WebUI is the same as the one I send to the SDK/API.

**Comment by venkatboddu** [comment]
@sjorge :-
Can you give more details on what patches have been applied to the Isilon Cluster on top of OneFS version 8.1.0?

**Comment by vboddui** [comment]
@sjorge :-
Can you give more details on what patches have been applied to the Isilon Cluster on top of OneFS version 8.1.0?

**Comment by sjorge** [comment]
Cluster Name: isirec (OneFS Version: v8.2.0.0) Node 1

With one patch:
- [8.2.0 UHC 2019-05] HealthCheck RUP

**Comment by nalinkanwar** [comment]
Hi @sjorge,

We've investigated this and found that it is a bug in the snapshot schedule API itself and would require change in OneFS code; 
The fix is done internally and will be included in upcoming patches.

Since this is not specifically a SDK bug, I'm closing this.
