### ISSUE TITLE
Dependency confusion security issue

### ISSUE THREAD

**Issue by bitsandsalsa** [Isilon/isilon_sdk#82]
The Python bindings packages distributed on PyPI are vulnerable to a form of [dependency confusion](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610). Because each bindings version is released under a different project in PyPI, anyone could masquerade as the next unreleased version by creating their own project on PyPI. For example, [isi-sdk-9-0-0](https://pypi.org/project/isi-sdk-9-0-0/) is the latest released version today, but someone could just create a isi-sdk-9-1-0 project.

The most common setup is for one project that has many release versions under it. There are [more options as well](https://github.com/pypa/packaging-problems/issues/114#issuecomment-348048622).

See also an [article from a vendor in the build artifact industry](https://jfrog.com/blog/yet-another-case-for-using-exclude-patterns-in-remote-repositories/).

**Comment by nalinkanwar** [comment]
Resolved in latest release v0.3.0
