### ISSUE TITLE
SmbSettingsGlobalSettingsAuditGlobalSaclItem fails spec file validation

### ISSUE THREAD

**Issue by cbrainerd** [Isilon/isilon_sdk#9]
>   "name": "SyntaxError",
>   "message": "Swagger schema validation failed.
>   Data does not match any schemas from 'oneOf' at #/paths//platform/1/protocols/smb/settings/global/put/parameters/0
>     Data does not match any schemas from 'oneOf' at #/paths//platform/1/protocols/smb/settings/global/put/parameters/0
>       Data does not match any schemas from 'anyOf' at #/schema/properties/audit_global_sacl/items
>         Data does not match any schemas from 'anyOf' at #/schema/properties/audit_global_sacl/items/properties/permission/items
>           **Array items are not unique (indexes 13 and 27) at #/properties/permission/items/enum**
>           Expected type array but found type object at #/properties/permission/items
>         Expected type array but found type object at #/schema/properties/audit_global_sacl/items
>       Missing required property: type at #/
>     Missing required property: $ref at #/paths//platform/1/protocols/smb/settings/global/put/parameters/0

In the permission enum, `delete_child` appears twice in the PAPI schema. This is OneFS bug 174819. It could be handled in create_swagger_config.py by deduplicating enums when generating the spec file. 

Found in v0.1.2 isi_sdk_7_2/output.json.

**Comment by Atomicology** [comment]
This issue is affecting the following Python packages: `isi_sdk_7_2`, `isi_sdk_8_0`, `isi_sdk_8_0_1`, and `isi_sdk_8_1_0`.
